# See https://github.com/mojombo/jekyll/wiki/Configuration

source:      .
destination: _site

safe:        true
url:         http://zest.apache.org
production_url: http://zest.apache.org

future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   date


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
